[package]
name = "upsi5"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
console_error_panic_hook = "0.1.7"
glam = "0.30.0"
marmalade = { path = "marmalade" }
wasm-bindgen-futures = "0.4.50"
